version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - gradle-cache:/home/gradle/.gradle
    environment:
      - TELEGRAM_BOT_TOKEN=7075351596:AAEaRzR7-PnEDgbDIsT__U8W8JItif-cPzs
      - TELEGRAM_CHAT_ID=81255808

volumes:
  gradle-cache:

